### ISSUE TITLE
Gather a gold standard for good names

### ISSUE THREAD

**Issue by wencanluo** [wencanluo/good-bad-names-for-GN#11]
- GNUB
- VertNet

**Comment by dimus** [comment]
I talked to Vertnet guys -- they say their 'golden checklist' is nearing completion and might be available in hours/days. And they want to talk on  Friday morning about it.

**Comment by wencanluo** [comment]
Great. You can check out the number of names from each data source.

https://drive.google.com/file/d/0B8ZDfTq5Ri9jMnNwSmN3QnpPdjQ/view

I think you can have a sense how many bad names might exist in the data
base.
The uBio NameBank has the most names, however, it is annotated as least
authority.

On Wed, Jun 24, 2015 at 9:18 AM, Dmitry Mozzherin notifications@github.com
wrote:

> I talked to Vertnet guys -- they say their 'golden checklist' is nearing
> completion and might be available in hours/days. And they want to talk on
> Friday morning about it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wencanluo/good-bad-names-for-GN/issues/11#issuecomment-114929987
> .

## 

Wencan Luo
CS Department- Univ. of Pittsburgh
210 S. Bouquet Street
5420 Sennott Square
Pittsburgh, PA 15260
E-mail: wencanluo.cn@gmail.com or wencan@cs.pitt.edu

**Comment by dimus** [comment]
here are names by nomenclatural rating of data sources: https://www.dropbox.com/sh/7dnk9hhidn9jefn/AAAHHbl4mwhxOGx5hSN5Xreka?dl=0
(I did not count wikispecies, as it has very unreliable harvesting)

names per file:

58310 nom2.txt
1045099 nom4.txt
2168455 nom0.txt
2453115 nom5.txt
5877811 nom3.txt
17388352 nom1.txt
23620582 all_names.txt

**Comment by dimus** [comment]
This is data for 1000 names which guys from VerNet cleaned up. They spent a lot of time working on it and they think it  is reasonably good, but not 100% good (which is also really hard to have for taxonomy, as people have different opinions)
https://github.com/tucotuco/DwCVocabs/wiki/VertNet-Taxonomy-Test-Set

**Comment by dimus** [comment]
https://github.com/tucotuco/DwCVocabs/blob/master/vocabs/tests/VertNetTaxonomyTestSet.csv

**Comment by wencanluo** [comment]
What does each column mean? especially 'sn-valid', and 'con-valid'
